In [246]:
import pandas as pd
#df=pd.read_table('dates.txt',header=None,names=['text'])
df=pd.read_csv('dates.txt',names='text')
len(df)

C:\Users\rajeshkc\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py:702: UserWarning: Duplicate names specified. This will raise an error in the future.
  return _read(filepath_or_buffer, kwds)

427

In [252]:
import pandas as pd

doc = []
with open('dates.txt') as file:
    for line in file:
        doc.append(line)

df = pd.Series(doc)
df

0           03/25/93 Total time of visit (in minutes):\n
1                         6/18/85 Primary Care Doctor:\n
2      sshe plans to move as of 7/8/71 In-Home Servic...
3                  7 on 9/27/75 Audit C Score Current:\n
4      2/6/96 sleep studyPain Treatment Pain Level (N...
5                      .Per 7/06/79 Movement D/O note:\n
6      4, 5/18/78 Patient's thoughts about current su...
7      10/24/89 CPT Code: 90801 - Psychiatric Diagnos...
8                           3/7/86 SOS-10 Total Score:\n
9               (4/10/71)Score-1Audit C Score Current:\n
10     (5/11/85) Crt-1.96, BUN-26; AST/ALT-16/22; WBC...
11                         4/09/75 SOS-10 Total Score:\n
12     8/01/98 Communication with referring physician...
13     1/26/72 Communication with referring physician...
14     5/24/1990 CPT Code: 90792: With medical servic...
15     1/25/2011 CPT Code: 90792: With medical servic...
16           4/12/82 Total time of visit (in minutes):\n
17          1; 10/13/1976 Audit C Score, Highest/Date:\n
18                   4, 4/24/98 Relevant Drug History:\n
19     ) 59 yo unemployed w referred by Urgent Care f...
20           7/21/98 Total time of visit (in minutes):\n
21                        10/21/79 SOS-10 Total Score:\n
22      3/03/90 CPT Code: 90792: With medical services\n
23      2/11/76 CPT Code: 90792: With medical services\n
24     07/25/1984 CPT Code: 90791: No medical services\n
25     4-13-82 Other Child Mental Health Outcomes Sca...
26      9/22/89 CPT Code: 90792: With medical services\n
27        9/02/76 CPT Code: 90791: No medical services\n
28                                9/12/71 [report_end]\n
29     10/24/86 Communication with referring physicia...
                             ...
470    y1983 Clinic Hospital, first hospitalization, ...
471    tProblems Urinary incontinence : mild urge inc...
472    .2010 - wife; nightmares and angry outbursts; ...
473         shx of TBI (1975) ISO MVA.Medical History:\n
474    sPatient reported losing three friends that pa...
475                        TSH okay in 2015 Prior EKG:\n
476    1989 Family Psych History: Family History of S...
477    oEnjoys animals, had a dog x 14 yrs who died i...
478    eHistory of small right parietal subgaleal hem...
479    sIn KEP Psychiatryfor therapy and medications ...
480    1. Esophageal cancer, dx: 2013, on FOLFOX with...
481                                        y1974 (all)\n
482    h/o restraining order by sister/mother in 1990...
483    sTexas Medical Center; Oklahoma for 2 weeks; 1...
484    Death of former partner in 2004 by overdose as...
485    Was "average" student.  "I didn't have too man...
486    Contemplating jumping off building - 1973 - di...
487    appendectomy s/p delivery 1992 Prior relevant ...
488    tProblems renal cell cancer : s/p nephrectomy ...
489        ran own business for 35 years, sold in 1985\n
490                                  Lab: B12 969 2007\n
491                                   )and 8mo in 2009\n
492    .Moved to USA in 1986. Suffered from malnutrit...
493                                              r1978\n
494    . Went to Emerson, in Newfane Alaska. Started ...
495    1979 Family Psych History: Family History of S...
496    therapist and friend died in ~2006 Parental/Ca...
497                         2008 partial thyroidectomy\n
498    sPt describes a history of sexual abuse as a c...
499    . In 1980, patient was living in Naples and de...
Length: 500, dtype: object

In [255]:
df['dateextract1']=df.str.findall(r'\d+[/-]\d+[/-]\d{2,4}')
#f['dateextract']=df['text'].str.findall(r'(\d{4})')
#df['dateextract']=df['text'].str.findall(r'(\d\d\d\d)')
#df.text.str.count(r'(\d+[/-]\d+[/-]\d+)').sum()
df['dateextract1']

0                 [03/25/93]
1                  [6/18/85]
2                   [7/8/71]
3                  [9/27/75]
4                   [2/6/96]
5                  [7/06/79]
6                  [5/18/78]
7                 [10/24/89]
8                   [3/7/86]
9                  [4/10/71]
10                 [5/11/85]
11                 [4/09/75]
12                 [8/01/98]
13                 [1/26/72]
14               [5/24/1990]
15               [1/25/2011]
16                 [4/12/82]
17              [10/13/1976]
18                 [4/24/98]
19                 [5/21/77]
20                 [7/21/98]
21                [10/21/79]
22                 [3/03/90]
23                 [2/11/76]
24              [07/25/1984]
25                 [4-13-82]
26                 [9/22/89]
27                 [9/02/76]
28                 [9/12/71]
29                [10/24/86]
                    ...
471                       []
472                       []
473                       []
474                       []
475                       []
476                       []
477                       []
478                       []
479                       []
480                       []
481                       []
482                       []
483                       []
484                       []
485                       []
486                       []
487                       []
488                       []
489                       []
490                       []
491                       []
492                       []
493                       []
494                       []
495                       []
496                       []
497                       []
498                       []
499                       []
dateextract1             NaN
Length: 501, dtype: object

In [258]:
df['dateextract2']=df.str.replace('(\d{5})','',regex=True)
df['dateextract3']=df['dateextract2'].str.findall(r'\d+[/-]\d+[/-]\d{2,4}')
df['dateextract3']

0                 [03/25/93]
1                  [6/18/85]
2                   [7/8/71]
3                  [9/27/75]
4                   [2/6/96]
5                  [7/06/79]
6                  [5/18/78]
7                 [10/24/89]
8                   [3/7/86]
9                  [4/10/71]
10                 [5/11/85]
11                 [4/09/75]
12                 [8/01/98]
13                 [1/26/72]
14               [5/24/1990]
15               [1/25/2011]
16                 [4/12/82]
17              [10/13/1976]
18                 [4/24/98]
19                 [5/21/77]
20                 [7/21/98]
21                [10/21/79]
22                 [3/03/90]
23                 [2/11/76]
24              [07/25/1984]
25                 [4-13-82]
26                 [9/22/89]
27                 [9/02/76]
28                 [9/12/71]
29                [10/24/86]
                    ...
472                       []
473                       []
474                       []
475                       []
476                       []
477                       []
478                       []
479                       []
480                       []
481                       []
482                       []
483                       []
484                       []
485                       []
486                       []
487                       []
488                       []
489                       []
490                       []
491                       []
492                       []
493                       []
494                       []
495                       []
496                       []
497                       []
498                       []
499                       []
dateextract1             NaN
dateextract2             NaN
Length: 502, dtype: object

In [242]:
#df['dateextract2']=df['text'].str.replace(r'\d{2}\d\d\d')
#df['dateextract2']=df['text'].str.replace('(\d{5})','',regex=True)

#df['dateextract2'].replace('(\d{5})','',regex=True,inplace=True)
df['dateextract3']=df['dateextract2'].str.findall(r'\d+[/-]\d+[/-]\d{2,4}|\d{4}')

df[['dateextract3','text']]

     dateextract3                                               text
0      [03/25/93]         03/25/93 Total time of visit (in minutes):
1       [6/18/85]                       6/18/85 Primary Care Doctor:
2        [7/8/71]  sshe plans to move as of 7/8/71 In-Home Servic...
3       [9/27/75]                7 on 9/27/75 Audit C Score Current:
4        [2/6/96]  2/6/96 sleep studyPain Treatment Pain Level (N...
5       [7/06/79]                    .Per 7/06/79 Movement D/O note:
6       [5/18/78]  4, 5/18/78 Patient's thoughts about current su...
7      [10/24/89]  10/24/89 CPT Code: 90801 - Psychiatric Diagnos...
8        [3/7/86]                         3/7/86 SOS-10 Total Score:
9       [4/10/71]             (4/10/71)Score-1Audit C Score Current:
10      [5/11/85]  (5/11/85) Crt-1.96, BUN-26; AST/ALT-16/22; WBC...
11      [4/09/75]                        4/09/75 SOS-10 Total Score:
12      [8/01/98]  8/01/98 Communication with referring physician...
13      [1/26/72]  1/26/72 Communication with referring physician...
14    [5/24/1990]   5/24/1990 CPT Code: 90792: With medical services
15    [1/25/2011]   1/25/2011 CPT Code: 90792: With medical services
16      [4/12/82]          4/12/82 Total time of visit (in minutes):
17   [10/13/1976]         1; 10/13/1976 Audit C Score, Highest/Date:
18      [4/24/98]                  4, 4/24/98 Relevant Drug History:
19      [5/21/77]  ) 59 yo unemployed w referred by Urgent Care f...
20      [7/21/98]          7/21/98 Total time of visit (in minutes):
21     [10/21/79]                       10/21/79 SOS-10 Total Score:
22      [3/03/90]     3/03/90 CPT Code: 90792: With medical services
23      [2/11/76]     2/11/76 CPT Code: 90792: With medical services
24   [07/25/1984]    07/25/1984 CPT Code: 90791: No medical services
25      [4-13-82]  4-13-82 Other Child Mental Health Outcomes Sca...
26      [9/22/89]     9/22/89 CPT Code: 90792: With medical services
27      [9/02/76]       9/02/76 CPT Code: 90791: No medical services
28      [9/12/71]                               9/12/71 [report_end]
29     [10/24/86]  10/24/86 Communication with referring physicia...
..            ...                                                ...
430        [1983]  y1983 Clinic Hospital, first hospitalization, ...
431        [1999]  tProblems Urinary incontinence : mild urge inc...
432        [2010]  .2010 - wife; nightmares and angry outbursts; ...
433        [1975]         shx of TBI (1975) ISO MVA.Medical History:
434        [1972]  sPatient reported losing three friends that pa...
435        [2015]                        TSH okay in 2015 Prior EKG:
436        [1989]  1989 Family Psych History: Family History of S...
437        [1994]  oEnjoys animals, had a dog x 14 yrs who died i...
438        [1993]  eHistory of small right parietal subgaleal hem...
439        [1996]  sIn KEP Psychiatryfor therapy and medications ...
440        [2013]  1. Esophageal cancer, dx: 2013, on FOLFOX with...
441        [1974]                                        y1974 (all)
442        [1990]  h/o restraining order by sister/mother in 1990...
443        [1995]  sTexas Medical Center; Oklahoma for 2 weeks; 1995
444        [2004]  Death of former partner in 2004 by overdose as...
445        [1987]  Was "average" student.  "I didn't have too man...
446        [1973]  Contemplating jumping off building - 1973 - di...
447        [1992]  appendectomy s/p delivery 1992 Prior relevant ...
448        [1977]  tProblems renal cell cancer : s/p nephrectomy ...
449        [1985]        ran own business for 35 years, sold in 1985
450        [2007]                                  Lab: B12 969 2007
451        [2009]                                   )and 8mo in 2009
452        [1986]  .Moved to USA in 1986. Suffered from malnutrit...
453        [1978]                                              r1978
454        [2002]  . Went to Emerson, in Newfane Alaska. Started ...
455        [1979]  1979 Family Psych History: Family History of S...
456        [2006]  therapist and friend died in ~2006 Parental/Ca...
457        [2008]                         2008 partial thyroidectomy
458        [2005]  sPt describes a history of sexual abuse as a c...
459        [1980]  . In 1980, patient was living in Naples and de...

[460 rows x 2 columns]